const Screens = {
  //AUTH SCREENS
  MOBILE_SIGN_UP_SCREEN: 'MOBILE_SIGN_UP_SCREEN',
  OTP_SCREEN: 'OTP_SCREEN',
  WELCOME_SCREEN: 'WELCOME_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
};

export default Screens;
